import "./list/changeNameTag.js"
import "./list/chats.js"
import "./list/isNewPlayer.js"
import "./list/kill.js"
import "./list/autoUpdate.js"
import "./list/allyRequestNotice_onJoin.js"
import "./list/displayTop.js"
import "./list/combatRestriction.js"